structure(list(method = "GET", url = "https://data.geopf.fr/wfs/ows?service=WFS&version=2.0.0&request=DescribeFeatureType&typeNames=badname", 
    status_code = 400L, headers = structure(list(date = "Wed, 25 Jun 2025 16:12:55 GMT", 
        `set-cookie` = "REDACTED", `content-type` = "application/xml", 
        `x-ratelimit-limit-second` = "1", `ratelimit-limit` = "30", 
        `www-authenticate` = "Key realm=\"kong\"", `cache-control` = "private, max-age=1814400", 
        `x-content-type-options` = "nosniff", `x-frame-options` = "SAMEORIGIN", 
        `content-security-policy` = "base-uri 'self'; form-action 'self'; default-src 'none'; child-src 'self'; connect-src 'self'; font-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self';, frame-ancestors 'self';", 
        `content-encoding` = "gzip", `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        `access-control-allow-origin` = "*", `access-control-allow-credentials` = "true", 
        `access-control-allow-methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `access-control-allow-headers` = "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Content-Disposition,Content-Length,X-Community", 
        `access-control-max-age` = "1728000", `transfer-encoding` = "chunked", 
        `x-iplb-request-id` = "2542CD10:434B_91EFC1E7:01BB_685C2007_B6FD5AAC:40EA", 
        `x-iplb-instance` = "61217"), class = "httr2_headers"), 
    body = charToRaw("<?xml version=\"1.0\" encoding=\"UTF-8\"?><ows:ExceptionReport xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:ows=\"http://www.opengis.net/ows/1.1\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"2.0.0\" xsi:schemaLocation=\"http://www.opengis.net/ows/1.1 https://data.geopf.fr/wfs/schemas/ows/1.1.0/owsAll.xsd\">\n  <ows:Exception exceptionCode=\"InvalidParameterValue\" locator=\"DescribeFeatureType\">\n    <ows:ExceptionText>Could not find type: {http://test_nl_kikoulol_allauch}badname</ows:ExceptionText>\n  </ows:Exception>\n</ows:ExceptionReport>\n"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
