---
title: "test"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(happign)
```

```{r}
library(sf)
library(terra)

filename = "temp"
resolution = 25
layer_name = "ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES"
format = "image/geotiff"

get_extension <- function(format) {
  ext <- switch(
     format,
     "image/jpeg" = ".jpg",
     "image/png" = ".png",
     "image/tiff" = ".tif",
     "image/geotiff" = ".tif",
     stop("Bad format, please check ",
          "`?get_wms_raster()`")
  )
}
construct_filename <- function(filename, resolution, layer_name, format) {

   ext <- get_extension(format)

   clean_names <- function(text){
      paste0(gsub("[^[:alnum:]]", '_',
                  paste0(text, "_", resolution,"m")),
             ext)
   }

   filename <- ifelse(is.null(filename),
                      clean_names(layer_name),
                      file.path(dirname(filename), clean_names(basename(filename))))

   filename <- normalizePath(enc2utf8(filename), mustWork = FALSE)
}

filename <- construct_filename(filename, resolution, layer_name, format)

urls <- c(
   "https://wxs.ign.fr/altimetrie/geoportail/r/wms?version=1.3.0&request=GetMap&format=image/geotiff&layers=ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES&styles=&width=1409&height=1958&crs=EPSG:2154&bbox=122533.640534,6793252.122258,129577.244682667,6803041.179502",
   "https://wxs.ign.fr/altimetrie/geoportail/r/wms?version=1.3.0&request=GetMap&format=image/geotiff&layers=ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES&styles=&width=1409&height=1958&crs=EPSG:2154&bbox=129577.244682667,6793252.122258,136620.848831333,6803041.179502"
)

Sys.setenv(GDAL_SKIP="DODS")

tiles_list <- NULL
for (i in seq_along(urls)) {
   message(i, "/", length(urls), " downloading...", sep = "")

   tmp <- tempfile(fileext = ".tif")
   
   gdal_utils(
      util = "translate",
      source = urls[i],
      destination = tmp,
      options = c("-a_srs", "EPSG:2154"))
   
   tiles_list <- c(tiles_list, tmp)
}

tiles_list <- normalizePath(tiles_list)
writeRaster(vrt(tiles_list, overwrite = TRUE), filename, overwrite = TRUE)

rast <- rast(filename)
file.remove(filename)
```

