structure(list(method = "GET", url = "https://apicarto.ign.fr/api/cadastre/parcelle?code_insee=29135&section=BR&numero=0010&source_ign=PCI&_start=0&_limit=500", 
    status_code = 200L, headers = structure(list(Date = "Sun, 11 Aug 2024 14:49:04 GMT", 
        `Content-Type` = "application/json; charset=utf-8", `Content-Length` = "147", 
        Connection = "keep-alive", `X-Powered-By` = "Express", 
        `Access-Control-Allow-Origin` = "*", `Cache-Control` = "private, no-cache, no-store, must-revalidate", 
        Expires = "-1", Pragma = "no-cache", Vary = "Origin", 
        `Access-Control-Allow-Credentials` = "true", ETag = "W/\"93-Jz1uwA56Yq6qnDdZxMOX3RPKE0o\"", 
        `Strict-Transport-Security` = "max-age=31536000; includeSubDomains"), class = "httr2_headers"), 
    body = charToRaw("{\"type\":\"FeatureCollection\",\"features\":[],\"totalFeatures\":0,\"numberMatched\":0,\"numberReturned\":0,\"timeStamp\":\"2024-08-11T14:49:04.628Z\",\"crs\":null}"), 
    request = structure(list(url = "https://apicarto.ign.fr/api/cadastre/parcelle?code_insee=29135&section=BR&numero=0010&source_ign=PCI&_start=0&_limit=500", 
        method = NULL, headers = list(), body = NULL, fields = list(), 
        options = list(ssl_verifypeer = 0), policies = list()), class = "httr2_request"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
