structure(list(method = "POST", url = "https://data.geopf.fr/wfs/ows?service=WFS&version=2.0.0&request=GetFeature&outputFormat=json&srsName=EPSG%3A4326&typeName=LIMITES_ADMINISTRATIVES_EXPRESS.LATEST%3Acommune&startindex=0&count=1000", 
    status_code = 200L, headers = structure(list(date = "Wed, 25 Jun 2025 16:12:12 GMT", 
        `set-cookie` = "REDACTED", `content-type` = "application/json;charset=UTF-8", 
        `x-ratelimit-limit-second` = "1", `ratelimit-limit` = "30", 
        `www-authenticate` = "Key realm=\"kong\"", `cache-control` = "private, max-age=1814400", 
        `x-content-type-options` = "nosniff", `x-frame-options` = "SAMEORIGIN", 
        `content-security-policy` = "base-uri 'self'; form-action 'self'; default-src 'none'; child-src 'self'; connect-src 'self'; font-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self';, frame-ancestors 'self';", 
        `content-disposition` = "inline; filename=commune.json", 
        `content-encoding` = "gzip", `strict-transport-security` = "max-age=31536000; includeSubDomains", 
        `access-control-allow-origin` = "*", `access-control-allow-credentials` = "true", 
        `access-control-allow-methods` = "GET, PUT, POST, DELETE, PATCH, OPTIONS", 
        `access-control-allow-headers` = "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Content-Disposition,Content-Length,X-Community", 
        `access-control-max-age` = "1728000", `transfer-encoding` = "chunked", 
        `x-iplb-request-id` = "2542CD10:49A0_91EFC1E7:01BB_685C1FDB_B6FBAAEC:40EA", 
        `x-iplb-instance` = "61217"), class = "httr2_headers"), 
    body = charToRaw("{\"type\":\"FeatureCollection\",\"features\":[],\"totalFeatures\":0,\"numberMatched\":0,\"numberReturned\":0,\"timeStamp\":\"2025-06-25T16:12:12.775Z\",\"crs\":null}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
